In [1]:
from spliter import StandartSpliter, BinarySpliter
from pandas_stats import TestingTTestPandas, TestingKStestPandas, TestingChiSquarePandas
import pandas as pd
import numpy as np
from typing import List

from scipy.stats import chi2_contingency

In [2]:
path = "../../data.csv"
df = pd.read_csv(path, index_col=0)
df.head()

,user_id,signup_month,treat,pre_spends,post_spends,age,gender,industry
0,0.0,0.0,0.0,519.5,424.666667,39.0,M,Logistics
1,1.0,0.0,0.0,500.5,423.111111,19.0,F,Logistics
2,2.0,0.0,0.0,499.0,423.444444,29.0,M,E-commerce
3,3.0,2.0,1.0,494.0,530.555556,38.0,M,E-commerce
4,4.0,9.0,1.0,455.0,451.888889,53.0,F,Logistics

In [3]:
group_num = 4
random_state = 21
k_splits = 3
target_columns = ["pre_spends", "post_spends"]

In [4]:
spliter = StandartSpliter(df, groups_num=group_num, random_state=random_state)
b_spliter = BinarySpliter(df, random_state=random_state, groups_num=group_num, k_splits=k_splits)
new_df = spliter.split()
b_new_df = b_spliter.split()

In [5]:
new_df.head(10)

,user_id,signup_month,treat,pre_spends,post_spends,age,gender,industry,group
0,0.0,0.0,0.0,519.5,424.666667,39.0,M,Logistics,0
1,1.0,0.0,0.0,500.5,423.111111,19.0,F,Logistics,1
2,2.0,0.0,0.0,499.0,423.444444,29.0,M,E-commerce,2
3,3.0,2.0,1.0,494.0,530.555556,38.0,M,E-commerce,0
4,4.0,9.0,1.0,455.0,451.888889,53.0,F,Logistics,0
5,5.0,1.0,1.0,536.0,518.333333,22.0,F,Logistics,0
6,6.0,4.0,1.0,493.5,500.777778,21.0,M,E-commerce,1
7,7.0,8.0,1.0,484.0,447.333333,69.0,F,E-commerce,2
8,8.0,0.0,0.0,473.5,413.222222,34.0,M,E-commerce,1
9,9.0,2.0,1.0,513.5,518.555556,39.0,M,E-commerce,2

In [6]:
b_new_df.head(10)

,user_id,signup_month,treat,pre_spends,post_spends,age,gender,industry,group
0,0.0,0.0,0.0,519.5,424.666667,39.0,M,Logistics,"[0, 1, 2]"
1,1.0,0.0,0.0,500.5,423.111111,19.0,F,Logistics,"[0, 0, 0]"
2,2.0,0.0,0.0,499.0,423.444444,29.0,M,E-commerce,"[1, 2, 1]"
3,3.0,2.0,1.0,494.0,530.555556,38.0,M,E-commerce,"[2, 0, 3]"
4,4.0,9.0,1.0,455.0,451.888889,53.0,F,Logistics,"[0, 0, 1]"
5,5.0,1.0,1.0,536.0,518.333333,22.0,F,Logistics,"[3, 3, 3]"
6,6.0,4.0,1.0,493.5,500.777778,21.0,M,E-commerce,"[3, 1, 1]"
7,7.0,8.0,1.0,484.0,447.333333,69.0,F,E-commerce,"[2, 1, 3]"
8,8.0,0.0,0.0,473.5,413.222222,34.0,M,E-commerce,"[3, 3, 2]"
9,9.0,2.0,1.0,513.5,518.555556,39.0,M,E-commerce,"[0, 1, 1]"

In [7]:
np.random.seed(21)
np.random.choice([0, 1, 2], (10, 5))

array([[1, 0, 0, 0, 0],
       [0, 0, 2, 1, 2],
       [0, 2, 0, 1, 1],
       [1, 1, 2, 2, 0],
       [2, 0, 2, 0, 0],
       [0, 0, 1, 1, 2],
       [1, 2, 2, 2, 0],
       [0, 2, 0, 1, 1],
       [0, 2, 0, 0, 1],
       [0, 0, 2, 2, 0]])

In [8]:
np.random.seed(21)
np.random.choice([0, 1, 2], (10,))

array([1, 0, 0, 0, 0, 0, 0, 2, 1, 2])

In [5]:
test = TestingTTestPandas(b_new_df,
                        #   ['industry', 'gender'],
                          target_columns,
                          "group",
                          group_num,
                          k_splits,
                          realization=2)
test.calculate()

{'pre_spends': {'split: 0 groups: 0, 1': {'p-value': 0.4751534419192619,
   'statistic': -0.7141792291523744,
   'pass': False},
  'split: 0 groups: 0, 2': {'p-value': 0.7894795982616651,
   'statistic': 0.2670024700713487,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.5238085893920328,
   'statistic': -0.6375361492766948,
   'pass': False},
  'split: 1 groups: 0, 1': {'p-value': 0.8706177650557403,
   'statistic': 0.16288329699627876,
   'pass': False},
  'split: 1 groups: 0, 2': {'p-value': 0.8036965895213416,
   'statistic': 0.2485804389266993,
   'pass': False},
  'split: 1 groups: 0, 3': {'p-value': 0.8289354773018001,
   'statistic': 0.21607950336018864,
   'pass': False},
  'split: 2 groups: 0, 1': {'p-value': 0.12482243400060297,
   'statistic': 1.5351269628356867,
   'pass': False},
  'split: 2 groups: 0, 2': {'p-value': 0.6726190603382751,
   'statistic': 0.4225842749901726,
   'pass': False},
  'split: 2 groups: 0, 3': {'p-value': 0.3988528437996387,
   'statistic': 0.8437514658856262,
   'pass': False}},
 'post_spends': {'split: 0 groups: 0, 1': {'p-value': 0.6032740890618573,
   'statistic': 0.5197347014864422,
   'pass': False},
  'split: 0 groups: 0, 2': {'p-value': 0.8953091378975969,
   'statistic': -0.13159681506766732,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.8816390559348947,
   'statistic': 0.1489003252539217,
   'pass': False},
  'split: 1 groups: 0, 1': {'p-value': 0.3343199017243733,
   'statistic': 0.9655546031393515,
   'pass': False},
  'split: 1 groups: 0, 2': {'p-value': 0.5270996473230206,
   'statistic': -0.6324884067961247,
   'pass': False},
  'split: 1 groups: 0, 3': {'p-value': 0.09210543399155954,
   'statistic': 1.6847503493668072,
   'pass': False},
  'split: 2 groups: 0, 1': {'p-value': 0.5405444347327603,
   'statistic': -0.6120363039811475,
   'pass': False},
  'split: 2 groups: 0, 2': {'p-value': 0.7080237430713844,
   'statistic': 0.3745356203823427,
   'pass': False},
  'split: 2 groups: 0, 3': {'p-value': 0.9785140980113682,
   'statistic': -0.026933327175081036,
   'pass': False}}}

In [6]:
test = TestingTTestPandas(new_df,
                        #   ['industry', 'gender'],
                          target_columns,
                          "group",
                          group_num,
                          1,
                          realization=1)
test.calculate()

{'pre_spends': {'split: 0 groups: 0, 1': {'p-value': 0.44908163298625836,
   'statistic': 0.7570134045500901,
   'pass': False},
  'split: 0 groups: 0, 2': {'p-value': 0.3619843173286219,
   'statistic': 0.9116838337852465,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.1482803613673557,
   'statistic': 1.4458798407629772,
   'pass': False}},
 'post_spends': {'split: 0 groups: 0, 1': {'p-value': 0.3894734400803448,
   'statistic': 0.8606562538397268,
   'pass': False},
  'split: 0 groups: 0, 2': {'p-value': 0.23115149643552188,
   'statistic': -1.1975608489828389,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.6902608733588274,
   'statistic': -0.3985266526759562,
   'pass': False}}}

In [7]:
test = TestingTTestPandas(new_df,
                        #   ['industry', 'gender'],
                          target_columns,
                          "group",
                          group_num,
                          1,
                          realization=0)
test.calculate()

{'pre_spends': {'split: 0 groups: 0, 1': {'p-value': 0.44908163298625836,
   'statistic': 0.7570134045500903,
   'pass': False},
  'split: 0 groups: 0, 2': {'p-value': 0.36198431732862235,
   'statistic': 0.9116838337852456,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.14828036136735598,
   'statistic': 1.4458798407629765,
   'pass': False}},
 'post_spends': {'split: 0 groups: 0, 1': {'p-value': 0.3894734400803448,
   'statistic': 0.8606562538397271,
   'pass': False},
  'split: 0 groups: 0, 2': {'p-value': 0.23115149643552171,
   'statistic': -1.1975608489828393,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.6902608733588274,
   'statistic': -0.3985266526759562,
   'pass': False}}}

In [6]:
target_categorical = ["gender", "industry"]

In [7]:
test = TestingChiSquarePandas(b_new_df,
                        #   ['industry', 'gender'],
                          target_categorical,
                          "group",
                          group_num,
                          k_splits,
                          realization=2)
test.calculate()

{'gender': {'split: 0 groups: 0, 1': {'p-value': 0.22222973088170977,
   'statistic': 1.489914469341334,
   'pass': False},
  'split: 0 groups: 0, 2': {'p-value': 0.23930010427868942,
   'statistic': 1.3847122701814774,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.4296463091540096,
   'statistic': 0.6237793612817554,
   'pass': False},
  'split: 1 groups: 0, 1': {'p-value': 0.7690930275301965,
   'statistic': 0.08617833209066497,
   'pass': False},
  'split: 1 groups: 0, 2': {'p-value': 0.38933881836032747,
   'statistic': 0.7410059767373799,
   'pass': False},
  'split: 1 groups: 0, 3': {'p-value': 0.4143788307633445,
   'statistic': 0.6662022114578949,
   'pass': False},
  'split: 2 groups: 0, 1': {'p-value': 0.6867096030132985,
   'statistic': 0.162670561805363,
   'pass': False},
  'split: 2 groups: 0, 2': {'p-value': 0.3922951552921755,
   'statistic': 0.7318160912983903,
   'pass': False},
  'split: 2 groups: 0, 3': {'p-value': 0.46641590137139133,
   'statistic': 0.5304543561319305,
   'pass': False}},
 'industry': {'split: 0 groups: 0, 1': {'p-value': 0.4843204845025041,
   'statistic': 0.4891191729442191,
   'pass': False},
  'split: 0 groups: 0, 2': {'p-value': 0.11588889408352171,
   'statistic': 2.4720201113023292,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.3850098864374861,
   'statistic': 0.7546439929442581,
   'pass': False},
  'split: 1 groups: 0, 1': {'p-value': 0.05527784650547452,
   'statistic': 3.673684872992183,
   'pass': False},
  'split: 1 groups: 0, 2': {'p-value': 0.9958263943442998,
   'statistic': 2.7361925906360932e-05,
   'pass': False},
  'split: 1 groups: 0, 3': {'p-value': 0.13566455935957064,
   'statistic': 2.226457735368314,
   'pass': False},
  'split: 2 groups: 0, 1': {'p-value': 0.6917591327434394,
   'statistic': 0.15718760329927886,
   'pass': False},
  'split: 2 groups: 0, 2': {'p-value': 0.8235150598555865,
   'statistic': 0.04974071769744497,
   'pass': False},
  'split: 2 groups: 0, 3': {'p-value': 0.35285533771211286,
   'statistic': 0.8631620032364831,
   'pass': False}}}

In [8]:
test = TestingChiSquarePandas(new_df,
                        #   ['industry', 'gender'],
                          target_categorical,
                          "group",
                          group_num,
                          1,
                          realization=1)
test.calculate()

{'gender': {'split: 0 groups: 0, 1': {'p-value': 0.2257720786612143,
   'statistic': 1.4673006186038786,
   'pass': False},
  'split: 0 groups: 0, 2': {'p-value': 0.14281467100289594,
   'statistic': 2.1473664889587525,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.66747153731034,
   'statistic': 0.1845739925338838,
   'pass': False}},
 'industry': {'split: 0 groups: 0, 1': {'p-value': 0.037479782497013024,
   'statistic': 4.328476305385938,
   'pass': True},
  'split: 0 groups: 0, 2': {'p-value': 0.2192117947514498,
   'statistic': 1.509523602780007,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.09197090147080535,
   'statistic': 2.8395336756154115,
   'pass': False}}}

In [9]:
test = TestingChiSquarePandas(new_df,
                        #   ['industry', 'gender'],
                          target_categorical,
                          "group",
                          group_num,
                          1,
                          realization=0)
test.calculate()

{'gender': {'split: 0 groups: 0, 1': {'p-value': 0.2257720786612143,
   'statistic': 1.4673006186038786,
   'pass': False},
  'split: 0 groups: 0, 2': {'p-value': 0.14281467100289594,
   'statistic': 2.1473664889587525,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.66747153731034,
   'statistic': 0.1845739925338838,
   'pass': False}},
 'industry': {'split: 0 groups: 0, 1': {'p-value': 0.037479782497013024,
   'statistic': 4.328476305385938,
   'pass': True},
  'split: 0 groups: 0, 2': {'p-value': 0.2192117947514498,
   'statistic': 1.509523602780007,
   'pass': False},
  'split: 0 groups: 0, 3': {'p-value': 0.09197090147080535,
   'statistic': 2.8395336756154115,
   'pass': False}}}

In [8]:
testign = b_new_df[["post_spends", "pre_spends", "group"]]
testign

      post_spends  pre_spends               group
0      424.666667       519.5    [-0.0, 1.0, 2.0]
1      423.111111       500.5  [-0.0, -0.0, -0.0]
2      423.444444       499.0     [1.0, 2.0, 1.0]
3      530.555556       494.0    [2.0, -0.0, 3.0]
4      451.888889       455.0   [-0.0, -0.0, 1.0]
...           ...         ...                 ...
9995   429.555556       490.0    [-0.0, 3.0, 1.0]
9996   414.666667       464.5    [3.0, 1.0, -0.0]
9997   411.666667       498.0   [-0.0, -0.0, 3.0]
9998   516.555556       528.0     [2.0, 2.0, 2.0]
9999   471.333333       507.5    [3.0, 1.0, -0.0]

[10000 rows x 3 columns]

In [132]:
def mean_over_split(df: pd.DataFrame,
                    group_column: str,
                    target_columns: List[str],
                    k_split: int):
    stats = (
                df
                .loc[:, [group_column] + target_columns]
                .groupby(df[group_column].map(lambda x: x[k_split]))
                [target_columns]
                # .mean()
                .agg(["mean", "count", "std"])
                # .values
            )
    # return stats

    stats.index = pd.MultiIndex.from_product([[k_split], stats.index], names=['split', 'group'])
    return stats
    
# result = (
#             pd.DataFrame({"k_splits" : range(k_splits)})
#             .apply(lambda x: mean_over_split(testign, "group", "pre_spends", x["k_splits"]), axis=1)
#         )

# result
# .value_counts()
#                             .unstack()
#                             .fillna(0)
result = pd.concat([mean_over_split(testign, "group", ["pre_spends", "post_spends"], split_idx) for split_idx in range(k_splits)])
result

             pre_spends                  post_spends
                   mean count        std        mean count        std
split group
0     -0.0   487.276615  2198  19.255987  452.312658  2198  39.575739
       1.0   487.689865  2299  19.530258  451.699241  2299  39.551991
       2.0   487.125993  2266  18.434033  452.469207  2266  39.891108
       3.0   487.641197  2238  18.831795  452.136729  2238  39.117014
1     -0.0   487.524623  2254  19.370163  452.739278  2254  39.790701
       1.0   487.431336  2170  18.697660  451.587916  2170  39.501682
       2.0   487.383421  2286  18.903170  453.487849  2286  39.951855
       3.0   487.401353  2291  19.089884  450.774189  2291  38.843308
2     -0.0   487.831707  2255  18.723557  452.069229  2255  39.596424
       1.0   486.967982  2280  19.160515  452.789620  2280  39.666639
       2.0   487.591179  2188  19.215787  451.624721  2188  39.501895
       3.0   487.359306  2278  18.969368  452.100819  2278  39.373016

In [11]:
def freq_over_splits(df: pd.DataFrame,
                     group_column: str,
                     target_columns: List[str],
                     k_split: int):
    stats = (
                    df
                    .loc[:, [group_column] + target_columns]
                    .groupby(df[group_column].map(lambda x: x[k_split]))
                    [target_columns]
                    .apply(lambda x: x.apply(pd.Series.value_counts))
                    .unstack()
                    .dropna(axis=1)

                    # .fillna(0)
                    # .assign(freq=lambda df_: sum([df_[column] for column in target_columns]))
                    # .loc[:, "freq"]
                    # .reset_index(1)
                    # .stack()
                    # .reset_index()
                    # .rename(columns=["label", "freq"])
                    # .unstack()
                    # .fillna(0)
                )

    stats.index = pd.MultiIndex.from_product([[k_split], stats.index], names=['split', 'group'])
    return stats
# freq_over_splits(b_new_df, "group", ["gender", "industry"], 0)
result = pd.concat([freq_over_splits(b_new_df, "group", ["gender", "industry"], split_idx) for split_idx in range(k_splits)])
result

             gender           industry
                  F       M E-commerce Logistics
split group
0     0      1129.0  1069.0     1088.0    1110.0
      1      1138.0  1161.0     1163.0    1136.0
      2      1123.0  1143.0     1176.0    1090.0
      3      1122.0  1116.0     1138.0    1100.0
1     0      1142.0  1112.0     1114.0    1140.0
      1      1110.0  1060.0     1136.0    1034.0
      2      1128.0  1158.0     1131.0    1155.0
      3      1132.0  1159.0     1184.0    1107.0
2     0      1113.0  1142.0     1134.0    1121.0
      1      1140.0  1140.0     1161.0    1119.0
      2      1109.0  1079.0     1092.0    1096.0
      3      1150.0  1128.0     1178.0    1100.0

In [61]:
def cdf_over_split(df: pd.DataFrame,
                   group_column: str,
                   target_columns: List[str],
                   k_split: int) -> pd.DataFrame:
    stats = (
        df
        .groupby(df[group_column].map(lambda x: x[k_split]))
        [target_columns]
        # .first()
        # .cumcount()
        .expanding()
        .count()
        # .apply(lambda x: x.apply(pd.Series.sort_values).apply(pd.DataFrame.cumcount()))
        # .unstack(level=0)
        # .reset_index(1)
        # .drop(columns="level_1")
        # .pivot()
    )
    # stats.index = pd.MultiIndex.from_product([[k_split], stats.index], names=["split", "index"])
    # stats.columns = pd.MultiIndex.from_tuples(list(map(lambda x: (x[1], x[0]), stats.columns)))
    return stats

In [62]:
cdf_over_split(testign, "group", ["pre_spends", "post_spends"], 0)

            pre_spends  post_spends
group
-0.0  0            1.0          1.0
      1            2.0          2.0
      4            3.0          3.0
      9            4.0          4.0
      11           5.0          5.0
...                ...          ...
 3.0  9990      2234.0       2234.0
      9992      2235.0       2235.0
      9993      2236.0       2236.0
      9996      2237.0       2237.0
      9999      2238.0       2238.0

[10000 rows x 2 columns]